### ISSUE TITLE
python numpy ValueError: operands could not be broadcast together with shapes

### ISSUE THREAD

**Issue by gikas1** [ncarraz/ESRGANplus#8]
I'm trying to train an x4, at iter: 500, during training, I get:

Traceback (most recent call last):
  File "/content/ESRGANplus/codes/train.py", line 173, in <module>
    main()
  File "/content/ESRGANplus/codes/train.py", line 148, in main
    avg_psnr += util.calculate_psnr(cropped_sr_img * 255, cropped_gt_img * 255)
  File "/content/ESRGANplus/codes/utils/util.py", line 111, in calculate_psnr
    mse = np.mean((img1 - img2)**2)
ValueError: operands could not be broadcast together with shapes (592,592,3) (600,600,3) 

Can you please help me spot the source of the problem and resolve this issue?
Thanks!

**Comment by gikas1** [comment]
I did a mistake on the HR imgs dimensions
